//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizadorQvetSuvesaPOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albaran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Albaran()
        {
            this.Albaran_Detalle = new HashSet<Albaran_Detalle>();
        }
    
        public long id { get; set; }
        public string NombreCliente { get; set; }
        public string NombreMascota { get; set; }
        public System.DateTime Fecha { get; set; }
        public long Id_Qvet_Migrado { get; set; }
        public Nullable<bool> facturado { get; set; }
        public string Cedula { get; set; }
        public Nullable<long> Id_Mascota_Qvet { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public string NHC_Mascota { get; set; }
        public Nullable<long> ID_Factura_Suvesa { get; set; }
        public string Responsable { get; set; }
        public string Tipo_Cliente { get; set; }
        public string CHIP_Mascota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Albaran_Detalle> Albaran_Detalle { get; set; }
    }
}
