//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizadorQvetSuvesaPOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albaran_Detalle
    {
        public long id { get; set; }
        public long idEncabezado { get; set; }
        public string Descripcion { get; set; }
        public long CodigoInternoQvet { get; set; }
        public decimal Cantidad { get; set; }
        public long IVA { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal Total { get; set; }
        public string Unidad { get; set; }
    
        public virtual Albaran Albaran { get; set; }
    }
}
