//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizadorQvetSuvesaPOS.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SINCRONIZADOREntities : DbContext
    {
        public SINCRONIZADOREntities()
            : base("name=SINCRONIZADOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albaran> Albarans { get; set; }
        public virtual DbSet<Albaran_Detalle> Albaran_Detalle { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<Bitacora_Albaran> Bitacora_Albaran { get; set; }
    }
}
