//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizadorQvetSuvesaPOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Albaran
    {
        public long Id { get; set; }
        public Nullable<long> Id_Albaran { get; set; }
        public string Usuario_Suvesa { get; set; }
        public System.DateTime Fecha_Hora { get; set; }
        public string Accion { get; set; }
        public string Observaciones { get; set; }
    }
}
